<?php
/**
 * OpenConnector EventsController.
 *
 * Controller for managing events and their subscriptions.
 *
 * @category Controller
 * @package  OCA\OpenConnector\Controller
 *
 * @author    Conduction Development Team <info@conduction.nl>
 * @copyright 2024 Conduction B.V.
 * @license   EUPL-1.2 https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * @version GIT: <git_id>
 *
 * @link https://www.OpenConnector.nl
 */

namespace OCA\OpenConnector\Controller;

use Exception;
use OCA\OpenConnector\Service\ActionAuthService;
use OCA\OpenConnector\Service\EventService;
use OCA\OpenConnector\Service\WebhookSignatureService;
use OCA\OpenConnector\Settings\OpenConnectorAdmin;
use OCA\OpenRegister\Service\ObjectService as OrObjectService;
use OCP\AppFramework\Controller;
use OCP\AppFramework\Db\DoesNotExistException;
use OCP\AppFramework\Http;
use OCP\AppFramework\Http\Attribute\AuthorizedAdminSetting;
use OCP\AppFramework\Http\Attribute\NoAdminRequired;
use OCP\AppFramework\Http\Attribute\NoCSRFRequired;
use OCP\AppFramework\Http\JSONResponse;
use OCP\IL10N;
use OCP\IRequest;
use OCP\IUserSession;

/**
 * Controller for managing events and their subscriptions.
 *
 * @SuppressWarnings(PHPMD.ShortVariable)
 * @SuppressWarnings(PHPMD.CouplingBetweenObjects)
 * @SuppressWarnings(PHPMD.TooManyPublicMethods)
 * @SuppressWarnings(PHPMD.UnusedFormalParameter)
 * @SuppressWarnings(PHPMD.UnusedLocalVariable)
 *
 * @spec openspec/changes/openconnector-webhook-signing/tasks.md#task-3
 */
class EventsController extends Controller
{
    /**
     * Constructor for the EventsController.
     *
     * @param string                  $appName          The name of the app.
     * @param IRequest                $request          The request object.
     * @param OrObjectService         $orObjectService  The OR object service.
     * @param EventService            $eventService     The event service.
     * @param IL10N                   $l                The localization service.
     * @param IUserSession            $userSession      The user session.
     * @param ActionAuthService       $actionAuth       The action authorization service.
     * @param WebhookSignatureService $signatureService Generates signing secrets.
     */
    public function __construct(
        $appName,
        IRequest $request,
        private readonly OrObjectService $orObjectService,
        private readonly EventService $eventService,
        private readonly IL10N $l,
        private readonly IUserSession $userSession,
        private readonly ActionAuthService $actionAuth,
        private readonly WebhookSignatureService $signatureService,
    ) {
        parent::__construct(appName: $appName, request: $request);

    }//end __construct()

    /**
     * Get all messages generated by an event.
     *
     * @param integer $id Event ID.
     *
     * @return JSONResponse List of messages.
     *
     * @NoAdminRequired
     * @NoCSRFRequired
     *
     * @spec openspec/changes/retrofit-2026-05-24-events-cloudevents/tasks.md#task-5
     */
    #[NoAdminRequired]
    #[NoCSRFRequired]
    public function messages(int $id): JSONResponse
    {
        $user = $this->userSession->getUser();
        if ($user === null) {
            return new JSONResponse(['error' => $this->l->t('Not authenticated')], Http::STATUS_UNAUTHORIZED);
        }

        $this->actionAuth->requireAction(user: $user, action: 'event.messages');

        try {
            $event = $this->orObjectService->find(id: (string) $id, register: 'openconnector', schema: 'event');
        } catch (DoesNotExistException $e) {
            return new JSONResponse(['error' => $this->l->t('Event not found')], 404);
        }

        // Get all messages for this event.
        $matches  = $this->orObjectService->findAll(
                config: [
                    'filters' => ['register' => 'openconnector', 'schema' => 'event_message', 'eventId' => (string) $id],
                    'limit'   => (int) $this->request->getParam('limit', 50),
                    'offset'  => (int) $this->request->getParam('offset', 0),
                ]
                );
        $messages = ($matches['results'] ?? $matches);

        return new JSONResponse(
                [
                    'event'    => $event->getObject(),
                    'messages' => $messages,
                ]
                );

    }//end messages()

    /**
     * Create a new subscription for events.
     *
     * @return JSONResponse The created subscription.
     *
     * @NoAdminRequired
     * @NoCSRFRequired
     *
     * @spec openspec/changes/retrofit-2026-05-24-events-cloudevents/tasks.md#task-5
     */
    #[NoAdminRequired]
    #[NoCSRFRequired]
    public function subscribe(): JSONResponse
    {
        $user = $this->userSession->getUser();
        if ($user === null) {
            return new JSONResponse(['error' => $this->l->t('Not authenticated')], Http::STATUS_UNAUTHORIZED);
        }

        $this->actionAuth->requireAction(user: $user, action: 'event.subscribe');

        try {
            $data = $this->request->getParams();

            // Remove internal fields.
            foreach ($data as $key => $value) {
                if (str_starts_with($key, '_') === true) {
                    unset($data[$key]);
                }
            }

            // Create subscription.
            $subscription = $this->orObjectService->saveObject(object: $data, register: 'openconnector', schema: 'event_subscription');

            return new JSONResponse($this->redactSubscription(subscription: $subscription->getObject()));
        } catch (Exception $e) {
            return new JSONResponse(['error' => $e->getMessage()], 400);
        }

    }//end subscribe()

    /**
     * Update an existing subscription.
     *
     * @param string $subscriptionId Subscription ID.
     *
     * @return JSONResponse The updated subscription.
     *
     * @NoAdminRequired
     * @NoCSRFRequired
     *
     * @spec openspec/changes/retrofit-2026-05-24-events-cloudevents/tasks.md#task-5
     */
    #[NoAdminRequired]
    #[NoCSRFRequired]
    public function updateSubscription(string $subscriptionId): JSONResponse
    {
        $user = $this->userSession->getUser();
        if ($user === null) {
            return new JSONResponse(['error' => $this->l->t('Not authenticated')], Http::STATUS_UNAUTHORIZED);
        }

        $this->actionAuth->requireAction(user: $user, action: 'event.update-subscription');

        try {
            $data = $this->request->getParams();

            // Remove internal fields.
            foreach ($data as $key => $value) {
                if (str_starts_with($key, '_') === true) {
                    unset($data[$key]);
                }
            }

            // Update subscription.
            $subscription = $this->orObjectService->saveObject(
                object: $data,
                register: 'openconnector',
                schema: 'event_subscription',
                uuid: (string) $subscriptionId
            );

            return new JSONResponse($this->redactSubscription(subscription: $subscription->getObject()));
        } catch (DoesNotExistException $e) {
            return new JSONResponse(['error' => $this->l->t('Subscription not found')], 404);
        } catch (Exception $e) {
            return new JSONResponse(['error' => $e->getMessage()], 400);
        }//end try

    }//end updateSubscription()

    /**
     * Delete a subscription.
     *
     * @param string $subscriptionId Subscription ID.
     *
     * @return JSONResponse Empty response.
     *
     * @NoAdminRequired
     * @NoCSRFRequired
     *
     * @spec openspec/changes/retrofit-2026-05-24-events-cloudevents/tasks.md#task-5
     */
    #[NoAdminRequired]
    #[NoCSRFRequired]
    public function unsubscribe(string $subscriptionId): JSONResponse
    {
        $user = $this->userSession->getUser();
        if ($user === null) {
            return new JSONResponse(['error' => $this->l->t('Not authenticated')], Http::STATUS_UNAUTHORIZED);
        }

        $this->actionAuth->requireAction(user: $user, action: 'event.unsubscribe');

        try {
            $subscription = $this->orObjectService->find(id: (string) $subscriptionId, register: 'openconnector', schema: 'event_subscription');
        } catch (DoesNotExistException $e) {
            return new JSONResponse(['error' => $this->l->t('Subscription not found')], 404);
        }

        $this->orObjectService->deleteObject(uuid: $subscription->getUuid());
        return new JSONResponse([]);

    }//end unsubscribe()

    /**
     * List all subscriptions.
     *
     * @return JSONResponse List of subscriptions.
     *
     * @NoAdminRequired
     * @NoCSRFRequired
     *
     * @spec openspec/changes/retrofit-2026-05-24-events-cloudevents/tasks.md#task-5
     */
    #[NoAdminRequired]
    #[NoCSRFRequired]
    public function subscriptions(): JSONResponse
    {
        $user = $this->userSession->getUser();
        if ($user === null) {
            return new JSONResponse(['error' => $this->l->t('Not authenticated')], Http::STATUS_UNAUTHORIZED);
        }

        $this->actionAuth->requireAction(user: $user, action: 'event.subscriptions');

        $filters = $this->request->getParams();

        // Remove internal fields.
        foreach ($filters as $key => $value) {
            if (str_starts_with($key, '_') === true) {
                unset($filters[$key]);
            }
        }

        $orFilters     = array_merge(['register' => 'openconnector', 'schema' => 'event_subscription'], $filters);
        $matches       = $this->orObjectService->findAll(
                config: [
                    'filters' => $orFilters,
                    'limit'   => (int) $this->request->getParam('limit', 50),
                    'offset'  => (int) $this->request->getParam('offset', 0),
                ]
                );
        $subscriptions = ($matches['results'] ?? $matches);

        // Redact signing secrets on every list read.
        $redacted = array_map(
            fn($subscription) => $this->redactSubscription(subscription: $subscription->getObject()),
            $subscriptions
        );

        return new JSONResponse(['results' => $redacted]);

    }//end subscriptions()

    /**
     * Get messages for a specific subscription.
     *
     * @param string $subscriptionId Subscription ID.
     *
     * @return JSONResponse List of messages.
     *
     * @NoAdminRequired
     * @NoCSRFRequired
     *
     * @spec openspec/changes/retrofit-2026-05-24-events-cloudevents/tasks.md#task-5
     */
    #[NoAdminRequired]
    #[NoCSRFRequired]
    public function subscriptionMessages(string $subscriptionId): JSONResponse
    {
        $user = $this->userSession->getUser();
        if ($user === null) {
            return new JSONResponse(['error' => $this->l->t('Not authenticated')], Http::STATUS_UNAUTHORIZED);
        }

        $this->actionAuth->requireAction(user: $user, action: 'event.subscription-messages');

        try {
            $subscription = $this->orObjectService->find(id: (string) $subscriptionId, register: 'openconnector', schema: 'event_subscription');
        } catch (DoesNotExistException $e) {
            return new JSONResponse(['error' => $this->l->t('Subscription not found')], 404);
        }

        // Get messages for this subscription.
        $matches  = $this->orObjectService->findAll(
                config: [
                    'filters' => ['register' => 'openconnector', 'schema' => 'event_message', 'subscriptionId' => (string) $subscriptionId],
                    'limit'   => (int) $this->request->getParam('limit', 50),
                    'offset'  => (int) $this->request->getParam('offset', 0),
                ]
                );
        $messages = ($matches['results'] ?? $matches);

        return new JSONResponse(
                [
                    'subscription' => $this->redactSubscription(subscription: $subscription->getObject()),
                    'messages'     => $messages,
                ]
                );

    }//end subscriptionMessages()

    /**
     * Pull events for a subscription (for pull-based subscriptions).
     *
     * @param string $subscriptionId Subscription ID.
     *
     * @return JSONResponse List of pending messages.
     *
     * @NoAdminRequired
     * @NoCSRFRequired
     *
     * @spec openspec/changes/retrofit-2026-05-24-events-cloudevents/tasks.md#task-3
     */
    #[NoAdminRequired]
    #[NoCSRFRequired]
    public function pull(string $subscriptionId): JSONResponse
    {
        $user = $this->userSession->getUser();
        if ($user === null) {
            return new JSONResponse(['error' => $this->l->t('Not authenticated')], Http::STATUS_UNAUTHORIZED);
        }

        $this->actionAuth->requireAction(user: $user, action: 'event.pull');

        try {
            $subscription = $this->orObjectService->find(id: (string) $subscriptionId, register: 'openconnector', schema: 'event_subscription');
        } catch (DoesNotExistException $e) {
            return new JSONResponse(['error' => $this->l->t('Subscription not found')], 404);
        }

        $subscriptionData = $subscription->getObject();
        if (($subscriptionData['style'] ?? '') !== 'pull') {
            return new JSONResponse(['error' => $this->l->t('Subscription is not pull-based')], 400);
        }

        $result = $this->eventService->pullEvents(
            subscription: $subscription,
            limit: $this->request->getParam('limit', 100),
            cursor: $this->request->getParam('cursor')
        );

        return new JSONResponse($result);

    }//end pull()

    /**
     * Generate a fresh signing secret for a push subscription.
     *
     * Admin-gated, CSRF-protected. The full `whsec_...` secret is returned in
     * THIS response only; every subsequent read surface redacts it.
     *
     * @param string $subscriptionId The subscription UUID.
     *
     * @return JSONResponse The full secret (once) plus the redacted subscription.
     *
     * @spec openspec/changes/openconnector-webhook-signing/tasks.md#task-3
     */
    #[AuthorizedAdminSetting(OpenConnectorAdmin::class)]
    public function generateSigningSecret(string $subscriptionId): JSONResponse
    {
        try {
            $subscription = $this->orObjectService->find(id: $subscriptionId, register: 'openconnector', schema: 'event_subscription');
        } catch (DoesNotExistException $e) {
            return new JSONResponse(['error' => $this->l->t('Subscription not found')], 404);
        }

        $data = $subscription->getObject();
        $protocolSettings = ($data['protocolSettings'] ?? []);

        $secret = $this->signatureService->generateSecret();
        $protocolSettings['signingSecret'] = $secret;
        // A first generate clears any rotation remnants.
        unset($protocolSettings['previousSigningSecret'], $protocolSettings['secretRotatedAt']);
        $data['protocolSettings'] = $protocolSettings;

        $saved = $this->orObjectService->saveObject(
            object: $data,
            register: 'openconnector',
            schema: 'event_subscription',
            uuid: $subscription->getUuid()
        );

        return new JSONResponse(
                [
                    'signingSecret' => $secret,
                    'subscription'  => $this->redactSubscription(subscription: $saved->getObject()),
                ]
                );

    }//end generateSigningSecret()

    /**
     * Rotate a subscription's signing secret.
     *
     * Moves the current secret to `previousSigningSecret`, stamps
     * `secretRotatedAt`, and returns the new secret once. Outbound deliveries
     * dual-sign until 24h after rotation.
     *
     * @param string $subscriptionId The subscription UUID.
     *
     * @return JSONResponse The new secret (once) plus the redacted subscription.
     *
     * @spec openspec/changes/openconnector-webhook-signing/tasks.md#task-3
     */
    #[AuthorizedAdminSetting(OpenConnectorAdmin::class)]
    public function rotateSigningSecret(string $subscriptionId): JSONResponse
    {
        try {
            $subscription = $this->orObjectService->find(id: $subscriptionId, register: 'openconnector', schema: 'event_subscription');
        } catch (DoesNotExistException $e) {
            return new JSONResponse(['error' => $this->l->t('Subscription not found')], 404);
        }

        $data = $subscription->getObject();
        $protocolSettings = ($data['protocolSettings'] ?? []);

        $current = ($protocolSettings['signingSecret'] ?? null);
        if ($current === null || $current === '') {
            return new JSONResponse(['error' => $this->l->t('No signing secret to rotate; generate one first')], 400);
        }

        $newSecret = $this->signatureService->generateSecret();
        $protocolSettings['previousSigningSecret'] = $current;
        $protocolSettings['signingSecret']         = $newSecret;
        $protocolSettings['secretRotatedAt']       = (new \DateTime())->format('c');
        $data['protocolSettings'] = $protocolSettings;

        $saved = $this->orObjectService->saveObject(
            object: $data,
            register: 'openconnector',
            schema: 'event_subscription',
            uuid: $subscription->getUuid()
        );

        return new JSONResponse(
                [
                    'signingSecret' => $newSecret,
                    'subscription'  => $this->redactSubscription(subscription: $saved->getObject()),
                ]
                );

    }//end rotateSigningSecret()

    /**
     * Redact signing secret material from a subscription object for any read.
     *
     * @param array $subscription The subscription object array.
     *
     * @return array The same array with secret fields replaced by a marker.
     *
     * @spec openspec/changes/openconnector-webhook-signing/tasks.md#task-3
     */
    private function redactSubscription(array $subscription): array
    {
        if (isset($subscription['protocolSettings']) === false || is_array($subscription['protocolSettings']) === false) {
            return $subscription;
        }

        foreach (['signingSecret', 'previousSigningSecret'] as $key) {
            if (isset($subscription['protocolSettings'][$key]) === true
                && $subscription['protocolSettings'][$key] !== ''
            ) {
                $subscription['protocolSettings'][$key] = '**********';
            }
        }

        return $subscription;

    }//end redactSubscription()
}//end class
