<?php

namespace OCA\OpenConnector\Controller;

use Exception;
use OCA\OpenRegister\Service\ObjectService as OrObjectService;
use OCP\AppFramework\Controller;
use OCP\AppFramework\Db\DoesNotExistException;
use OCP\AppFramework\Http\TemplateResponse;
use OCP\AppFramework\Http\JSONResponse;
use OCP\IAppConfig;
use OCP\IL10N;
use OCP\IRequest;
use OCA\OpenConnector\Service\EventService;

/**
 * Controller for managing events and their subscriptions
 *
 * @SuppressWarnings(PHPMD.ShortVariable)
 * @SuppressWarnings(PHPMD.CouplingBetweenObjects)
 * @SuppressWarnings(PHPMD.TooManyPublicMethods)
 * @SuppressWarnings(PHPMD.UnusedFormalParameter)
 * @SuppressWarnings(PHPMD.UnusedLocalVariable)
 */
class EventsController extends Controller
{
    /**
     * Constructor for the EventsController
     *
     * @param string          $appName         The name of the app
     * @param IRequest        $request         The request object
     * @param IAppConfig      $config          The app configuration object
     * @param OrObjectService $orObjectService The OR object service
     * @param EventService    $eventService    The event service
     * @param IL10N           $l               The localization service
     */
    public function __construct(
        $appName,
        IRequest $request,
        private readonly IAppConfig $config,
        private readonly OrObjectService $orObjectService,
        private readonly EventService $eventService,
        private readonly IL10N $l
    ) {
        parent::__construct($appName, $request);
    }//end __construct()

    /**
     * Returns the template of the main app's page
     *
     * This method renders the main page of the application, adding any necessary data to the template.
     *
     * @NoAdminRequired
     * @NoCSRFRequired
     *
     * @return TemplateResponse The rendered template response
     */
    public function page(): TemplateResponse
    {
        return new TemplateResponse(
            'openconnector',
            'index',
            []
        );
    }//end page()

    /**
     * Get all messages generated by an event
     *
     * @NoAdminRequired
     * @NoCSRFRequired
     *
     * @param  int $id Event ID
     * @return JSONResponse List of messages
     */
    public function messages(int $id): JSONResponse
    {
        try {
            $event = $this->orObjectService->find(id: (string) $id, register: 'openconnector', schema: 'event');
        } catch (DoesNotExistException $e) {
            return new JSONResponse(['error' => $this->l->t('Event not found')], 404);
        }

        // Get all messages for this event
        $matches  = $this->orObjectService->findAll(
                config: [
                    'filters' => ['register' => 'openconnector', 'schema' => 'event_message', 'eventId' => (string) $id],
                    'limit'   => (int) $this->request->getParam('limit', 50),
                    'offset'  => (int) $this->request->getParam('offset', 0),
                ]
                );
        $messages = $matches['results'] ?? $matches;

        return new JSONResponse(
                [
                    'event'    => $event->getObject(),
                    'messages' => $messages,
                ]
                );
    }//end messages()

    /**
     * Create a new subscription for events
     *
     * @NoAdminRequired
     * @NoCSRFRequired
     *
     * @return JSONResponse The created subscription
     */
    public function subscribe(): JSONResponse
    {
        try {
            $data = $this->request->getParams();

            // Remove internal fields
            foreach ($data as $key => $value) {
                if (str_starts_with($key, '_')) {
                    unset($data[$key]);
                }
            }

            // Create subscription
            $subscription = $this->orObjectService->saveObject(object: $data, register: 'openconnector', schema: 'event_subscription');

            return new JSONResponse($subscription->getObject());
        } catch (Exception $e) {
            return new JSONResponse(['error' => $e->getMessage()], 400);
        }
    }//end subscribe()

    /**
     * Update an existing subscription
     *
     * @NoAdminRequired
     * @NoCSRFRequired
     *
     * @param  string $subscriptionId Subscription ID
     * @return JSONResponse The updated subscription
     */
    public function updateSubscription(string $subscriptionId): JSONResponse
    {
        try {
            $data = $this->request->getParams();

            // Remove internal fields
            foreach ($data as $key => $value) {
                if (str_starts_with($key, '_')) {
                    unset($data[$key]);
                }
            }

            // Update subscription
            $subscription = $this->orObjectService->saveObject(object: $data, register: 'openconnector', schema: 'event_subscription', uuid: (string) $subscriptionId);

            return new JSONResponse($subscription->getObject());
        } catch (DoesNotExistException $e) {
            return new JSONResponse(['error' => $this->l->t('Subscription not found')], 404);
        } catch (Exception $e) {
            return new JSONResponse(['error' => $e->getMessage()], 400);
        }
    }//end updateSubscription()

    /**
     * Delete a subscription
     *
     * @NoAdminRequired
     * @NoCSRFRequired
     *
     * @param  string $subscriptionId Subscription ID
     * @return JSONResponse Empty response
     */
    public function unsubscribe(string $subscriptionId): JSONResponse
    {
        try {
            $subscription = $this->orObjectService->find(id: (string) $subscriptionId, register: 'openconnector', schema: 'event_subscription');
        } catch (DoesNotExistException $e) {
            return new JSONResponse(['error' => $this->l->t('Subscription not found')], 404);
        }

        $this->orObjectService->deleteObject(uuid: $subscription->getUuid());
        return new JSONResponse([]);
    }//end unsubscribe()

    /**
     * List all subscriptions
     *
     * @NoAdminRequired
     * @NoCSRFRequired
     *
     * @return JSONResponse List of subscriptions
     */
    public function subscriptions(): JSONResponse
    {
        $filters = $this->request->getParams();

        // Remove internal fields
        foreach ($filters as $key => $value) {
            if (str_starts_with($key, '_')) {
                unset($filters[$key]);
            }
        }

        $orFilters     = array_merge(['register' => 'openconnector', 'schema' => 'event_subscription'], $filters);
        $matches       = $this->orObjectService->findAll(
                config: [
                    'filters' => $orFilters,
                    'limit'   => (int) $this->request->getParam('limit', 50),
                    'offset'  => (int) $this->request->getParam('offset', 0),
                ]
                );
        $subscriptions = $matches['results'] ?? $matches;

        return new JSONResponse(['results' => $subscriptions]);
    }//end subscriptions()

    /**
     * Get messages for a specific subscription
     *
     * @NoAdminRequired
     * @NoCSRFRequired
     *
     * @param  string $subscriptionId Subscription ID
     * @return JSONResponse List of messages
     */
    public function subscriptionMessages(string $subscriptionId): JSONResponse
    {
        try {
            $subscription = $this->orObjectService->find(id: (string) $subscriptionId, register: 'openconnector', schema: 'event_subscription');
        } catch (DoesNotExistException $e) {
            return new JSONResponse(['error' => $this->l->t('Subscription not found')], 404);
        }

        // Get messages for this subscription
        $matches  = $this->orObjectService->findAll(
                config: [
                    'filters' => ['register' => 'openconnector', 'schema' => 'event_message', 'subscriptionId' => (string) $subscriptionId],
                    'limit'   => (int) $this->request->getParam('limit', 50),
                    'offset'  => (int) $this->request->getParam('offset', 0),
                ]
                );
        $messages = $matches['results'] ?? $matches;

        return new JSONResponse(
                [
                    'subscription' => $subscription->getObject(),
                    'messages'     => $messages,
                ]
                );
    }//end subscriptionMessages()

    /**
     * Pull events for a subscription (for pull-based subscriptions)
     *
     * @NoAdminRequired
     * @NoCSRFRequired
     *
     * @param  string $subscriptionId Subscription ID
     * @return JSONResponse List of pending messages
     */
    public function pull(string $subscriptionId): JSONResponse
    {
        try {
            $subscription = $this->orObjectService->find(id: (string) $subscriptionId, register: 'openconnector', schema: 'event_subscription');
        } catch (DoesNotExistException $e) {
            return new JSONResponse(['error' => $this->l->t('Subscription not found')], 404);
        }

        $subscriptionData = $subscription->getObject();
        if (($subscriptionData['style'] ?? '') !== 'pull') {
            return new JSONResponse(['error' => $this->l->t('Subscription is not pull-based')], 400);
        }

        $result = $this->eventService->pullEvents(
            subscription: $subscription,
            limit: $this->request->getParam('limit', 100),
            cursor: $this->request->getParam('cursor')
        );

        return new JSONResponse($result);
    }//end pull()
}//end class
